; M5Stack StickS3 + SZDX DX-LR30-900M22SP Pin Header / 插针款, not DX-LR30-900M22SP development board / 开发板
[env:m5stack-sticks3-dx-lr30-900m22sp-pin-header]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = M5STACK_STICKS3_DX_LR30_900M22SP_PIN_HEADER
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = M5Stack StickS3 + DX-LR30-900M22SP Pin Header
custom_meshtastic_tags = M5Stack, SZDX
custom_meshtastic_partition_scheme = 8MB
custom_meshtastic_url = https://docs.m5stack.com/en/core/StickS3

extends = esp32s3_base
board = m5stack-sticks3
board_check = true
board_build.partitions = default_8MB.csv
upload_protocol = esptool
build_flags =
  ${esp32s3_base.build_flags}
  -D M5STACK_STICKS3_DX_LR30_900M22SP_PIN_HEADER
  -D PRIVATE_HW
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -I variants/esp32s3/m5stack_sticks3_dx_lr30_900m22sp_pin_header
lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-st7789 packageName=https://github.com/meshtastic/st7789 gitBranch=main
  https://github.com/meshtastic/st7789/archive/5180423ae2dbf5885168a8bfb308c7fb7eff6930.zip
