name: Build M5Stack StickS3 DX-LR30 Pin Header

on:
  pull_request:
    paths:
      - .github/workflows/build_m5stack_sticks3_dx_lr30_900m22sp_pin_header.yml
      - variants/esp32s3/m5stack_sticks3_dx_lr30_900m22sp_pin_header/**
  push:
    paths:
      - .github/workflows/build_m5stack_sticks3_dx_lr30_900m22sp_pin_header.yml
      - variants/esp32s3/m5stack_sticks3_dx_lr30_900m22sp_pin_header/**
  workflow_dispatch:
    inputs:
      environment:
        description: PlatformIO environment to build
        required: true
        default: m5stack-sticks3-dx-lr30-900m22sp-pin-header
        type: choice
        options:
          - m5stack-sticks3-dx-lr30-900m22sp-pin-header

permissions: read-all

jobs:
  build:
    name: Compile m5stack-sticks3-dx-lr30-900m22sp-pin-header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Compile firmware
        env:
          PIO_ENV: ${{ github.event.inputs.environment || 'm5stack-sticks3-dx-lr30-900m22sp-pin-header' }}
        run: platformio run -e "$PIO_ENV"
